//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starcounter.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starcounter.Validation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} was never added to this validator.
        /// </summary>
        public static string Validator_PropertyNeverAdded {
            get {
                return ResourceManager.GetString("Validator_PropertyNeverAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error presenter has not been set. Make sure to call {0} at least once.
        /// </summary>
        public static string ValidatorBuilder_ErrorPresenterMissing {
            get {
                return ResourceManager.GetString("ValidatorBuilder_ErrorPresenterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} has already been added to this validator.
        /// </summary>
        public static string ValidatorBuilder_PropertyAlreadyAdded {
            get {
                return ResourceManager.GetString("ValidatorBuilder_PropertyAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} has no public getter.
        /// </summary>
        public static string ValidatorBuilder_PropertyGetterMissing {
            get {
                return ResourceManager.GetString("ValidatorBuilder_PropertyGetterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View-model has not been set. Make sure to call {0} at least once.
        /// </summary>
        public static string ValidatorBuilder_ViewModelMissing {
            get {
                return ResourceManager.GetString("ValidatorBuilder_ViewModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View-Model {0} has no public property called {1}.
        /// </summary>
        public static string ValidatorBuilder_ViewModelMissingProperty {
            get {
                return ResourceManager.GetString("ValidatorBuilder_ViewModelMissingProperty", resourceCulture);
            }
        }
    }
}
